name: meu_app
description: "LITGO5 Flutter App - Sistema de Match Jurídico Inteligente"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.7.0

  # Navigation
  go_router: ^14.8.1

  # Backend Integration
  supabase_flutter: ^2.7.0
  http: ^1.2.0

  # UI Components
  lucide_icons: ^0.257.0

  # Utilities
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/ 