apiVersion: 1

notifiers:
  - name: slack-critical
    type: slack
    uid: slack_critical
    org_id: 1
    is_default: false
    send_reminder: true
    frequency: 10m
    settings:
      url: ${SLACK_WEBHOOK_URL}
      channel: "#litgo5-alerts"
      username: "LITGO5 Monitor"
      title: "🚨 ALERTA CRÍTICO - LITGO5"
      text: |
        **{{ .CommonLabels.alertname }}**
        
        **Severidade:** {{ .CommonLabels.severity }}
        **Equipe:** {{ .CommonLabels.team }}
        
        **Detalhes:**
        {{ range .Alerts }}
        - {{ .Annotations.summary }}
        - {{ .Annotations.description }}
        {{ end }}
        
        **Dashboard:** [Ver Dashboard]({{ .ExternalURL }})
      iconEmoji: ":rotating_light:"
      
  - name: slack-warning
    type: slack
    uid: slack_warning
    org_id: 1
    is_default: false
    send_reminder: true
    frequency: 30m
    settings:
      url: ${SLACK_WEBHOOK_URL}
      channel: "#litgo5-monitoring"
      username: "LITGO5 Monitor"
      title: "⚠️ Alerta - LITGO5"
      text: |
        **{{ .CommonLabels.alertname }}**
        
        **Severidade:** {{ .CommonLabels.severity }}
        **Equipe:** {{ .CommonLabels.team }}
        
        **Detalhes:**
        {{ range .Alerts }}
        - {{ .Annotations.summary }}
        {{ end }}
      iconEmoji: ":warning:" 