export const mockDetailedCases = [
  {
    id: '001',
    title: 'Rescisão Trabalhista Indevida',
    description: 'Demissão sem justa causa com irregularidades no cálculo de verbas rescisórias. Cliente trabalhou por 5 anos na empresa e não recebeu todos os direitos.',
    area: 'Direito Trabalhista',
    subarea: 'Rescisão Contratual',
    status: 'active' as const,
    priority: 'high' as const,
    urgency_hours: 8,
    risk_level: 'medium' as const,
    confidence_score: 92,
    consultation_fee: 350,
    representation_fee: 2500,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-20T14:30:00Z',
    lawyer: {
      id: 'lawyer-001',
      name: 'Dr. Carlos Mendes',
      specialty: 'Direito Trabalhista',
      oab: 'SP 123.456',
      rating: 4.8,
      experience_years: 12,
      success_rate: 89,
      phone: '(11) 99999-9999',
      email: 'carlos.mendes@advocacia.com',
      location: 'São Paulo, SP',
      avatar: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=400'
    },
    documents: [
      { id: 'doc1', case_id: '001', name: 'Relatório da Consulta.pdf', file_path: '', file_size: 2300000, file_type: 'pdf', uploaded_by: 'user1', uploaded_at: '2024-01-16T12:30:00Z' },
      { id: 'doc2', case_id: '001', name: 'Modelo de Petição.pdf', file_path: '', file_size: 1100000, file_type: 'pdf', uploaded_by: 'user1', uploaded_at: '2024-01-17T06:15:00Z' },
      { id: 'doc3', case_id: '001', name: 'Checklist de Documentos.pdf', file_path: '', file_size: 800000, file_type: 'pdf', uploaded_by: 'user1', uploaded_at: '2024-01-16T13:00:00Z' },
    ],
    tasks: [
        { id: 'task1', title: 'Enviar documentos', description: 'Contrato de trabalho, carta de demissão e comprovantes', due_date: '2024-01-24T23:59:59Z', priority: 'high', status: 'pending'},
        { id: 'task2', title: 'Análise dos documentos', description: 'Advogado analisará a documentação enviada', due_date: '2024-01-27T23:59:59Z', priority: 'medium', status: 'pending'},
        { id: 'task3', title: 'Elaboração de petição', description: 'Preparação da ação trabalhista', due_date: '2024-02-04T23:59:59Z', priority: 'medium', status: 'pending'},
    ],
    unread_messages: 3,
    ai_analysis: {
      summary: 'Com base nas informações fornecidas, identifica-se uma possível demissão sem justa causa com irregularidades no pagamento rescisória...',
      required_documents: ['Contrato de trabalho', 'Carta de demissão', 'Comprovantes de pagamento'],
      risk_description: 'Risco baixo. Documentação sólida e jurisprudência favorável. Recomenda-se prosseguir com a consulta especializada.',
    }
  },
  {
    id: '002',
    title: 'Revisão de Contrato Empresarial',
    description: 'Análise e revisão de contrato de prestação de serviços B2B com cláusulas abusivas identificadas pela IA.',
    area: 'Direito Empresarial',
    subarea: 'Contratos Comerciais',
    status: 'summary_generated' as const,
    priority: 'medium' as const,
    urgency_hours: 72,
    risk_level: 'low' as const,
    confidence_score: 85,
    consultation_fee: 500,
    representation_fee: 4500,
    created_at: '2024-01-18T09:00:00Z',
    updated_at: '2024-01-19T16:20:00Z',
    documents: [
      { id: 'doc5', case_id: '002', name: 'Contrato Original.pdf', file_path: '', file_size: 1800000, file_type: 'pdf', uploaded_by: 'user2', uploaded_at: '2024-01-18T09:30:00Z' },
      { id: 'doc6', case_id: '002', name: 'Proposta de Alteração.docx', file_path: '', file_size: 512000, file_type: 'docx', uploaded_by: 'user2', uploaded_at: '2024-01-18T15:45:00Z' },
    ],
    tasks: [],
    unread_messages: 0,
    ai_analysis: {
      summary: 'Análise e revisão de contrato de prestação de serviços B2B',
      required_documents: [],
      risk_description: 'Risco baixo. Contrato com cláusulas padrão de mercado.',
    }
  },
  {
    id: '003',
    title: 'Ação de Indenização por Danos Morais',
    description: 'Cliente vítima de acidente de trânsito busca indenização por danos morais e materiais. Caso com alta complexidade.',
    area: 'Direito Civil',
    subarea: 'Responsabilidade Civil',
    status: 'pending' as const,
    priority: 'high' as const,
    urgency_hours: 48,
    risk_level: 'high' as const,
    confidence_score: 78,
    consultation_fee: 400,
    representation_fee: 6000,
    created_at: '2024-01-20T14:00:00Z',
    updated_at: '2024-01-20T14:00:00Z',
    lawyer: {
      id: 'lawyer-002',
      name: 'Dra. Ana Paula Santos',
      specialty: 'Direito Civil',
      oab: 'RJ 987.654',
      rating: 4.9,
      experience_years: 15,
      success_rate: 94,
      phone: '(21) 88888-8888',
      email: 'ana.santos@escritorio.com.br',
      location: 'Rio de Janeiro, RJ',
      avatar: 'https://images.pexels.com/photos/3760263/pexels-photo-3760263.jpeg?auto=compress&cs=tinysrgb&w=400'
    },
    documents: [
      { id: 'doc7', case_id: '003', name: 'Boletim de Ocorrência.pdf', file_path: '', file_size: 1200000, file_type: 'pdf', uploaded_by: 'user3', uploaded_at: '2024-01-20T14:30:00Z' },
      { id: 'doc8', case_id: '003', name: 'Laudos Médicos.pdf', file_path: '', file_size: 2800000, file_type: 'pdf', uploaded_by: 'user3', uploaded_at: '2024-01-20T15:00:00Z' },
      { id: 'doc9', case_id: '003', name: 'Fotos do Acidente.zip', file_path: '', file_size: 15000000, file_type: 'zip', uploaded_by: 'user3', uploaded_at: '2024-01-20T15:30:00Z' },
    ],
    tasks: [],
    unread_messages: 1,
    ai_analysis: {
      summary: 'Cliente vítima de acidente de trânsito busca indenização',
      required_documents: ['Boletim de Ocorrência', 'Laudos Médicos', 'Orçamentos de reparo'],
      risk_description: 'Risco alto devido à necessidade de comprovação de nexo causal.',
    }
  },
  {
    id: '004',
    title: 'Questão Previdenciária - Aposentadoria',
    description: 'Revisão de benefício INSS para aposentadoria por tempo de contribuição com possibilidade de aumento do valor.',
    area: 'Direito Previdenciário',
    subarea: 'Benefícios INSS',
    status: 'completed' as const,
    priority: 'low' as const,
    urgency_hours: 168, // 1 semana
    risk_level: 'low' as const,
    confidence_score: 95,
    consultation_fee: 250,
    representation_fee: 1800,
    created_at: '2024-01-10T08:00:00Z',
    updated_at: '2024-01-25T17:00:00Z',
    lawyer: {
      id: 'lawyer-003',
      name: 'Dr. Roberto Oliveira',
      specialty: 'Direito Previdenciário',
      oab: 'MG 456.789',
      rating: 4.7,
      experience_years: 20,
      success_rate: 91,
      phone: '(31) 77777-7777',
      email: 'roberto.oliveira@previdencia.adv.br',
      location: 'Belo Horizonte, MG'
    },
    documents: [
      { id: 'doc10', case_id: '004', name: 'CNIS - Cadastro Nacional.pdf', file_path: '', file_size: 890000, file_type: 'pdf', uploaded_by: 'user4', uploaded_at: '2024-01-10T09:00:00Z' },
      { id: 'doc11', case_id: '004', name: 'Carta de Concessão.pdf', file_path: '', file_size: 445000, file_type: 'pdf', uploaded_by: 'user4', uploaded_at: '2024-01-10T10:30:00Z' },
    ],
    tasks: [],
    unread_messages: 0,
    ai_analysis: {
      summary: 'Revisão de benefício INSS para aposentadoria por tempo de contribuição',
      required_documents: ['CNIS', 'Carta de Concessão', 'Documentos de Identificação'],
      risk_description: 'Risco baixo, processo administrativo com altas chances de êxito.',
    }
  }
];
