groups:
- name: litgo_alerts
  interval: 30s
  rules:
  
  # =============================================================================
  # ALERTAS CRÍTICOS - Resposta imediata necessária
  # =============================================================================
  
  - alert: HighErrorRate
    expr: rate(triage_requests_total{status="error"}[5m]) > 0.1
    for: 2m
    labels:
      severity: critical
      team: backend
    annotations:
      summary: "Alta taxa de erro em triagem ({{ $value | humanizePercentage }})"
      description: "Taxa de erro nas requisições de triagem está acima de 10% por mais de 2 minutos."
      runbook: "https://wiki.litgo.com/runbooks/high-error-rate"
  
  - alert: AllJobsFailing
    expr: sum(rate(job_executions_total{status="failed"}[5m])) by (job_name) > 0.5
    for: 5m
    labels:
      severity: critical
      team: devops
    annotations:
      summary: "Job {{ $labels.job_name }} falhando continuamente"
      description: "O job {{ $labels.job_name }} está falhando em mais de 50% das execuções."
  
  - alert: NoMatchesFound
    expr: rate(matches_found_total[10m]) == 0
    for: 10m
    labels:
      severity: critical
      team: backend
    annotations:
      summary: "Nenhum match encontrado nos últimos 10 minutos"
      description: "O sistema não está encontrando matches, possível problema no algoritmo."

  # =============================================================================
  # ALERTAS B2B LAW FIRMS - Sistema de Escritórios
  # =============================================================================
  
  - alert: B2BRankingHighLatency
    expr: histogram_quantile(0.99, rate(litgo_match_rank_duration_seconds_bucket{entity="firm"}[5m])) > 0.2
    for: 3m
    labels:
      severity: critical
      team: backend
      component: b2b_ranking
    annotations:
      summary: "Latência alta no ranking B2B ({{ $value }}s)"
      description: "P99 da latência do ranking B2B está acima de 200ms por mais de 3 minutos."
      runbook: "https://wiki.litgo.com/runbooks/b2b-ranking-latency"
      dashboard: "https://grafana.litgo.com/d/b2b-funnel"
  
  - alert: B2BMatchingFailure
    expr: rate(litgo_match_rank_total{entity="firm",status="error"}[5m]) > 0.05
    for: 2m
    labels:
      severity: critical
      team: backend
      component: b2b_matching
    annotations:
      summary: "Alta taxa de falha no matching B2B ({{ $value | humanizePercentage }})"
      description: "Taxa de erro no matching B2B está acima de 5% por mais de 2 minutos."
      runbook: "https://wiki.litgo.com/runbooks/b2b-matching-failure"
  
  - alert: B2BSuccessRateLow
    expr: rate(match_b2b_success_rate[1h]) < 0.7
    for: 15m
    labels:
      severity: warning
      team: backend
      component: b2b_success
    annotations:
      summary: "Taxa de sucesso B2B baixa ({{ $value | humanizePercentage }})"
      description: "Taxa de sucesso B2B está abaixo de 70% na última hora."
      runbook: "https://wiki.litgo.com/runbooks/b2b-success-rate"
  
  - alert: FirmEndpointHighLatency
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{endpoint=~"/firms.*"}[5m])) > 1.0
    for: 5m
    labels:
      severity: warning
      team: backend
      component: firms_api
    annotations:
      summary: "Latência alta nos endpoints de escritórios ({{ $value }}s)"
      description: "P95 da latência dos endpoints /firms/* está acima de 1s por mais de 5 minutos."
      runbook: "https://wiki.litgo.com/runbooks/firms-api-latency"
  
  - alert: FirmDataStale
    expr: time() - firm_kpis_last_updated_timestamp > 86400
    for: 1h
    labels:
      severity: warning
      team: backend
      component: firm_data
    annotations:
      summary: "Dados de KPIs de escritórios desatualizados"
      description: "KPIs de escritórios não são atualizados há mais de 24 horas."
      runbook: "https://wiki.litgo.com/runbooks/firm-data-stale"
  
  - alert: ConflictScanTimeout
    expr: rate(conflict_scan_timeout_total[5m]) > 0.1
    for: 3m
    labels:
      severity: warning
      team: backend
      component: conflict_scan
    annotations:
      summary: "Timeouts frequentes no conflict scan ({{ $value | humanizePercentage }})"
      description: "Conflict scan está apresentando timeouts em mais de 10% das requisições."
      runbook: "https://wiki.litgo.com/runbooks/conflict-scan-timeout"
  
  - alert: FeatureECalculationError
    expr: rate(feature_e_calculation_errors_total[5m]) > 0.02
    for: 2m
    labels:
      severity: warning
      team: backend
      component: feature_e
    annotations:
      summary: "Erros no cálculo da Feature-E ({{ $value | humanizePercentage }})"
      description: "Feature-E (Firm Reputation) está apresentando erros em mais de 2% dos cálculos."
      runbook: "https://wiki.litgo.com/runbooks/feature-e-errors"
  
  # =============================================================================
  # ALERTAS DE ALTA SEVERIDADE - Ação necessária em breve
  # =============================================================================
  
  - alert: HighLatency
    expr: histogram_quantile(0.95, rate(triage_duration_seconds_bucket[5m])) > 30
    for: 5m
    labels:
      severity: warning
      team: backend
    annotations:
      summary: "Latência alta em triagem (P95: {{ $value | humanizeDuration }})"
      description: "95% das triagens estão levando mais de 30 segundos."
  
  - alert: ManyOffersExpiring
    expr: rate(offers_created_total[1h]) > 0 and (active_offers_count / rate(offers_created_total[1h])) < 0.3
    for: 15m
    labels:
      severity: warning
      team: business
    annotations:
      summary: "Muitas ofertas expirando sem resposta"
      description: "Menos de 30% das ofertas estão sendo respondidas."
  
  - alert: LowCacheHitRate
    expr: cache_hit_rate{cache_type="redis"} < 0.5
    for: 10m
    labels:
      severity: warning
      team: devops
    annotations:
      summary: "Taxa de acerto do cache Redis baixa ({{ $value | humanizePercentage }})"
      description: "Cache Redis com menos de 50% de hit rate, possível problema de configuração."
  
  # =============================================================================
  # ALERTAS DE EQUIDADE - Distribuição injusta
  # =============================================================================
  
  - alert: UnfairDistribution
    expr: equity_distribution_gini > 0.4
    for: 30m
    labels:
      severity: warning
      team: business
    annotations:
      summary: "Distribuição de casos desigual (Gini: {{ $value | humanize }})"
      description: "Coeficiente de Gini acima de 0.4 indica distribuição muito desigual."
  
  - alert: LawyersOverloaded
    expr: average_lawyer_load_percent > 90
    for: 15m
    labels:
      severity: warning
      team: business
    annotations:
      summary: "Advogados sobrecarregados em {{ $labels.area }}"
      description: "Carga média dos advogados em {{ $labels.area }} está acima de 90%."
  
  # =============================================================================
  # ALERTAS DE JOBS - Problemas com tarefas agendadas
  # =============================================================================
  
  - alert: JobNotRunning
    expr: time() - job_last_success_timestamp > 86400
    for: 1h
    labels:
      severity: warning
      team: devops
    annotations:
      summary: "Job {{ $labels.job_name }} não executa há mais de 24h"
      description: "Última execução bem-sucedida foi há {{ $value | humanizeDuration }}."
  
  - alert: EquityJobFailed
    expr: increase(job_executions_total{job_name="calculate_equity", status="failed"}[1h]) > 0
    for: 5m
    labels:
      severity: warning
      team: backend
    annotations:
      summary: "Job de cálculo de equidade falhou"
      description: "O job de equidade falhou, distribuição pode ficar comprometida."
  
  # =============================================================================
  # ALERTAS DE DEPENDÊNCIAS EXTERNAS
  # =============================================================================
  
  - alert: ExternalAPITimeout
    expr: rate(external_api_duration_seconds_count{quantile="0.95"}[5m]) > 10
    for: 5m
    labels:
      severity: warning
      team: backend
    annotations:
      summary: "API externa {{ $labels.service }} com timeout frequente"
      description: "{{ $labels.service }} está com P95 > 10s, considere usar fallback."
  
  - alert: HighFallbackUsage
    expr: rate(fallback_usage_total[5m]) > 0.2
    for: 10m
    labels:
      severity: info
      team: backend
    annotations:
      summary: "Alto uso de fallback para {{ $labels.service }}"
      description: "Fallback sendo usado em mais de 20% das requisições."
  
  # =============================================================================
  # ALERTAS DE CAPACIDADE - Problemas de escala
  # =============================================================================
  
  - alert: QueueBacklog
    expr: queue_size > 1000
    for: 5m
    labels:
      severity: warning
      team: devops
    annotations:
      summary: "Fila {{ $labels.queue_name }} com backlog alto"
      description: "Mais de 1000 itens na fila, possível gargalo de processamento."
  
  - alert: FewLawyersAvailable
    expr: lawyers_available_count < 5
    for: 30m
    labels:
      severity: info
      team: business
    annotations:
      summary: "Poucos advogados disponíveis em {{ $labels.area }}"
      description: "Apenas {{ $value }} advogados disponíveis, considere recrutar mais."
  
  # =============================================================================
  # ALERTAS DE SISTEMA - Saúde geral
  # =============================================================================
  
  - alert: SystemHealthLow
    expr: system_health_score < 80
    for: 10m
    labels:
      severity: warning
      team: devops
    annotations:
      summary: "Saúde do sistema degradada ({{ $value }}/100)"
      description: "Score de saúde abaixo de 80, verificar métricas individuais."
  
  - alert: DatabaseSlowQueries
    expr: histogram_quantile(0.95, rate(database_query_duration_seconds_bucket[5m])) > 1
    for: 5m
    labels:
      severity: warning
      team: backend
    annotations:
      summary: "Queries lentas no banco (P95: {{ $value | humanizeDuration }})"
      description: "95% das queries estão levando mais de 1 segundo."

# =============================================================================
# REGRAS DE GRAVAÇÃO - Pré-calcular métricas complexas
# =============================================================================

- name: litgo_recording_rules
  interval: 30s
  rules:
  
  # Taxa de sucesso por estratégia
  - record: triage:success_rate:5m
    expr: |
      sum(rate(triage_requests_total{status="success"}[5m])) by (strategy) /
      sum(rate(triage_requests_total[5m])) by (strategy)
  
  # Latência média por preset
  - record: matching:latency_avg:5m
    expr: |
      rate(matching_duration_seconds_sum[5m]) /
      rate(matching_duration_seconds_count[5m])
  
  # Taxa de conversão de ofertas
  - record: offers:conversion_rate:1h
    expr: |
      sum(rate(contracts_signed_total[1h])) /
      sum(rate(offers_created_total[1h]))
  
  # Carga média do sistema
  - record: system:load_average:5m
    expr: |
      avg(average_lawyer_load_percent) 