name: meu_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  supabase_flutter: ^2.5.3
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  get_it: ^7.7.0
  equatable: ^2.0.7
  lucide_icons: ^0.257.0
  injectable: ^2.3.2
  http: ^1.2.1
  go_router: ^14.2.0
  image_picker: ^1.1.2
  file_picker: ^8.0.3
  dotted_border: ^2.1.0
  # UI e Animações
  flutter_animate: ^4.2.0+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  dio: ^5.8.0+1
  google_sign_in: ^6.2.1
  
  # Formulários e Validação

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
