name: meu_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Adicionadas para o sistema de parcerias e modelos de dados
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_html: ^3.0.0-beta.2 # Para renderizar o contrato
  fl_chart: ^0.68.0 # Para gráficos do dashboard
  # Fim das dependências adicionadas
  
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_maps_flutter: ^2.7.0
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.5.8
  timeago: ^3.6.1
  intl: ^0.19.0
  dartz: ^0.10.1
  connectivity_plus: ^6.0.3
  http: ^1.1.0
  
  # Dependências de UI e ícones
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0
  file_picker: ^8.0.0+1
  bloc_concurrency: ^0.2.5
  
  # Dependências para LocationPicker
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  
  # Firebase Remote Config para feature flags
  firebase_remote_config: ^4.4.6
  firebase_core: ^2.32.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Adicionadas para geração de código
  freezed: ^2.5.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

  # Adicionadas para testes
  bloc_test: ^9.1.7
  mocktail: ^1.0.3
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  # Fim das dependências adicionadas

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
