name: meu_app
description: "LITIG-1 - Sistema Jurídico Avançado"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  
  # Network & API
  dio: ^5.4.3
  http: ^1.2.0
  
  # UI Components
  lucide_icons: ^0.250.0
  cached_network_image: ^3.3.1
  
  # Date & Time
  intl: ^0.19.0
  timeago: ^3.6.1
  
  # Navigation
  go_router: ^14.2.7
  
  # Firebase
  firebase_core: ^3.15.2
  firebase_remote_config: ^5.5.0
  firebase_messaging: ^15.1.5
  
  # Utils
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  dartz: ^0.10.1
  get_it: ^7.7.0
  
  # Fonts & UI
  google_fonts: ^6.2.1
  
  # Database & Auth
  supabase_flutter: ^2.5.8
  
  # Connectivity & Network
  connectivity_plus: ^6.0.3
  
  # Additional dependencies
  bloc_concurrency: ^0.2.5
  json_annotation: ^4.9.0
  flutter_local_notifications: ^19.3.1
  permission_handler: ^12.0.1
  web_socket_channel: ^2.4.0
  flutter_webrtc: ^0.11.7
  socket_io_client: ^2.0.3+1
  # google_mlkit_text_recognition: ^0.13.0
  # google_mlkit_document_scanner: ^0.2.0
  image_picker: ^1.0.4
  image: ^4.1.3
  cpf_cnpj_validator: ^2.0.0
  file_picker: ^8.0.0+1
  google_maps_flutter: ^2.7.0
  flutter_rating_bar: ^4.0.1
  geolocator: ^12.0.0
  geocoding: ^2.1.1
  url_launcher: ^6.2.1
  fl_chart: ^0.68.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/