name: meu_app
description: "LITIG-1 - Sistema Jurídico Avançado"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.20.5
  equatable: ^2.0.5
  
  # Network & API
  dio: ^5.4.3
  http: ^1.2.0
  
  # UI Components
  lucide_icons: ^0.257.0
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  
  # Date & Time
  intl: ^0.20.2
  timeago: ^3.6.1
  
  # Navigation
  go_router: ^16.0.0
  
  # Firebase
  firebase_core: ^3.15.2
  firebase_remote_config: ^5.5.0
  firebase_messaging: ^15.1.5
  
  # Utils
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  
  # Fonts & UI
  google_fonts: ^6.2.1
  
  # Database & Auth
  supabase_flutter: ^2.5.8
  
  # Connectivity & Network
  connectivity_plus: ^6.0.3
  
  # Additional dependencies
  bloc_concurrency: ^0.3.0
  json_annotation: ^4.9.0
  flutter_local_notifications: ^19.3.1
  permission_handler: ^12.0.1
  web_socket_channel: ^3.0.3
  flutter_webrtc: ^0.14.2
  socket_io_client: ^3.1.2
  
  # Database - SQLite for local cache
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Analytics & Metrics
  device_info_plus: ^11.5.0
  package_info_plus: ^8.0.0
  # google_mlkit_text_recognition: ^0.13.0
  # google_mlkit_document_scanner: ^0.2.0
  image_picker: ^1.0.4
  image: ^4.1.3
  cpf_cnpj_validator: ^2.0.0
  file_picker: ^10.2.0
  google_maps_flutter: ^2.7.0
  flutter_rating_bar: ^4.0.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  fl_chart: ^1.0.0
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  table_calendar: ^3.2.0
  
  # Rich Text Editor
  flutter_quill: ^11.4.2
  html_editor_enhanced: ^2.5.1
  flutter_html: ^3.0.0-beta.2
  
  # Voice Messages  
  flutter_sound: ^9.2.13
  just_audio: ^0.10.4
  audioplayers: ^6.0.0
  record: ^6.0.0
  firebase_analytics: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.8
  mockito: ^5.4.4
  bloc_test: ^10.0.0
  injectable: ^2.3.2
  bloc: ^9.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/